import uuid
import base64
import sqlite3
import os
from datetime import datetime, UTC, timedelta
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from dotenv import load_dotenv

#Some of the code in this file was generated by Claude Sonnet 4.5
#any line that has a comment with * in it was generated or partially generated



class KeyManager:
    __instance = None

    def __new__(cls, *args, **kwargs):
        if cls.__instance is None:
            # Create a new instance using the superclass's __new__
            cls.__instance = super(KeyManager, cls).__new__(cls)
            # You can add initial configuration here if needed
        return cls.__instance

    def __init__(self, conn: sqlite3.Connection):
        if not hasattr(self, 'conn'):
            load_dotenv()
            self.keypassword = os.getenv("KEYPASSWORD")
            self.conn = conn
            self.cursor = self.conn.cursor()
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS keys(
                kid INTEGER PRIMARY KEY AUTOINCREMENT,
                key BLOB NOT NULL,
                exp INTEGER NOT NULL,
                crt INTEGER NOT NULL
                )''')
        else:
            print("Warning the key manager singleton was created twice, there may be an error.")
        
    def create_key_pair(self):

        EXPONENT = 65537

        private_key = rsa.generate_private_key(
            public_exponent=EXPONENT,
            key_size=2048,
        )

        public_key = private_key.public_key()


        numbers = public_key.public_numbers()
        exponent = numbers.e
        mod = numbers.n

        def _int_to_base64url(value: int) -> str:
            byte_len = (value.bit_length() + 7) // 8 or 1
            raw = value.to_bytes(byte_len, "big")
            return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")

        jkw = {
            "kty": "RSA",
            "alg": "RS256",
            "use": "sig",
            "e": _int_to_base64url(exponent),
            "n": _int_to_base64url(mod),
        }

        return (private_key, public_key, jkw)

    def create_key(self, experation: datetime, debug=False):
        """The Experation date must be in UTC or will be converted to UTC
        """

        experation = experation.astimezone(UTC)
        print(experation)
        if (experation < datetime.now(UTC)) and not debug:
            print("Warning experation date is in the past!")
            raise IOError

        private_key, public_key, jwk = self.create_key_pair()
        serial = private_key.private_bytes(encoding=serialization.Encoding.PEM, format=serialization.PrivateFormat.PKCS8,encryption_algorithm=serialization.BestAvailableEncryption(self.keypassword.encode("utf-8")))

        self.cursor.execute("INSERT INTO keys (key, exp, crt) VALUES (?, ?, ?)", (serial,experation.timestamp(), datetime.now(UTC).timestamp(),))
        self.conn.commit()
        kid = self.cursor.lastrowid
        jwk['kid'] = kid
        return (public_key, jwk)

    def all_valid_keys(self):
        '''
        This provides a list of all valid keys that are in the manager.
        '''

        res = self.cursor.execute("SELECT * FROM keys WHERE exp > ?", (datetime.now(UTC).timestamp(),))
        keys = res.fetchall()
        return keys

    def newest_valid_key(self):
        valid_keys = self.all_valid_keys()
        if not valid_keys:
            return {}
        return max(valid_keys, key=lambda row: row[3])
    
    def newest_expired_key(self):
        expired_keys = self.cursor.execute("SELECT * FROM keys WHERE exp <= ?", (datetime.now(UTC).timestamp(),))
        if not expired_keys:
            return {}
        return max(expired_keys, key=lambda row: row[3])

if __name__ == "__main__":
    import time
    print("Running")
    conn = sqlite3.connect("totally_not_my_privateKeys.db")
    key_manager = KeyManager(conn)
    key_manager.create_key(datetime.now(UTC) + timedelta(hours=1))
    time.sleep(3)
    key_manager.create_key(datetime.now(UTC) + timedelta(hours=1))
    print(key_manager.newest_valid_key())
    time.sleep(3)
    key_manager.create_key(datetime.now(UTC) + timedelta(hours=1))
    print(key_manager.all_valid_keys())
