import keygen
from datetime import datetime, UTC

'''Some of the code in this file was generated by Claude Sonnet 4.5
any line that has a comment with * in it was generated or partially generated
'''


class KeyManager:
    keys = []
    def __init__(self):
        pass
    def create_key(self, experation: datetime, debug=False):
        """The Experation date must be in UTC or will be converted to UTC
        """

        experation = experation.astimezone(UTC)
        print(experation)
        if (experation < datetime.now(UTC)) and not debug:
            print("Warning experation date is in the past!")
            raise IOError

        private_key, public_key, jwk = keygen.create_key_pair()
        self.keys.append({"private_key": private_key, "public_key": public_key, "jwk": jwk, "exp": experation, "tcreat": datetime.now(UTC)})

    def all_valid_keys(self):
        '''
        This provides a list of all valid keys that are in the manager.
        '''

        keys = []
        for key in self.keys:
            if key['exp'] > datetime.now(tz=UTC):
                keys.append(key)
        return keys

    def newest_valid_key(self):
        '''
        * This function was almost entirly created by AI
        This grabs the newest valid key and returns it

        '''
        now = datetime.now(UTC)
        valid_keys = [key for key in self.keys if key["exp"] > now]
        if not valid_keys:
            return {}
        return max(valid_keys, key=lambda key: key["tcreat"])
    
    def newest_expired_key(self):
        '''
        * This function was almost entirly created by AI
        This grabs the newest expired key and returns it
        '''
        now = datetime.now(UTC)
        expired_keys = [key for key in self.keys if key["exp"] <= now]
        if not expired_keys:
            return {}
        return max(expired_keys, key=lambda key: key["tcreat"])

