import base64
import sqlite3
import os
from datetime import datetime, UTC, timedelta
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from dotenv import load_dotenv

#Some of the code in this file was generated by Claude Sonnet 4.5
#any line that has a comment with * in it was generated or partially generated



class KeyManager:

    def __init__(self):
        """Initialize environment-backed settings and ensure the keys table exists."""
        load_dotenv()
        self.databasepath =  os.getenv("DATABASENAME")
        self.keypassword = os.getenv("KEYPASSWORD")
        # Store encrypted private keys and expiration timestamps in SQLite.
        with sqlite3.connect(self.databasepath) as conn:
            cursor = conn.cursor()
            cursor.execute('''CREATE TABLE IF NOT EXISTS keys(
                kid INTEGER PRIMARY KEY AUTOINCREMENT,
                key BLOB NOT NULL,
                exp INTEGER NOT NULL
                )''')

    def create_key_pair(self):
        """Generate an RSA key pair and return both keys plus a public JWK payload."""

        EXPONENT = 65537

        private_key = rsa.generate_private_key(
            public_exponent=EXPONENT,
            key_size=2048,
        )

        public_key = private_key.public_key()


        numbers = public_key.public_numbers()
        exponent = numbers.e
        mod = numbers.n

        jkw = {
            "kty": "RSA",
            "alg": "RS256",
            "use": "sig",
            # JWKS requires base64url-encoded RSA public numbers.
            "e": self._int_to_base64url(exponent),
            "n": self._int_to_base64url(mod),
        }

        return (private_key, public_key, jkw)

    def create_key(self, experation: datetime, debug=False):
        """The Experation date must be in UTC or will be converted to UTC
        """

        experation = experation.astimezone(UTC)
        print(experation)
        if (experation < datetime.now(UTC)) and not debug:
            print("Warning experation date is in the past!")
            raise IOError

        private_key, public_key, jwk = self.create_key_pair()
        # Persist only the encrypted private key; public JWK is derived when needed.
        serial = private_key.private_bytes(encoding=serialization.Encoding.PEM, format=serialization.PrivateFormat.PKCS8,encryption_algorithm=serialization.BestAvailableEncryption(self.keypassword.encode("utf-8")))
        with sqlite3.connect(self.databasepath) as conn:
            cursor = conn.cursor()
            cursor.execute("INSERT INTO keys (key, exp) VALUES (?, ?)", (serial,int(experation.timestamp()),))
            conn.commit()
            kid = cursor.lastrowid
        jwk['kid'] = str(kid)
        return (public_key, jwk)

    @staticmethod
    def _int_to_base64url(value: int) -> str:
        """Convert an integer to unpadded base64url text for JWK numeric fields."""
        # Remove '=' padding to produce RFC 7517-compatible base64url values.
        byte_len = (value.bit_length() + 7) // 8 or 1
        raw = value.to_bytes(byte_len, "big")
        return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")

    def key_row_to_jwk(self, row):
        """Convert a database key row into its public JWKS representation."""
        # Rebuild the public JWK from the stored private key row.
        kid, key_blob, _exp = row
        private_key = serialization.load_pem_private_key(
            key_blob,
            self.keypassword.encode("utf-8")
        )
        numbers = private_key.public_key().public_numbers()
        return {
            "kty": "RSA",
            "alg": "RS256",
            "use": "sig",
            "e": self._int_to_base64url(numbers.e),
            "n": self._int_to_base64url(numbers.n),
            "kid": str(kid),
        }

    def all_valid_keys(self):
        '''
        This provides a list of all valid keys that are in the manager.
        '''
        with sqlite3.connect(self.databasepath) as conn:
            cursor = conn.cursor()
            res = cursor.execute(
                # Newest key first so signing/selection is deterministic.
                "SELECT * FROM keys WHERE exp > ? ORDER BY kid DESC",
                (int(datetime.now(UTC).timestamp()),)
            )
        keys = res.fetchall()
        return keys

    def valid_key(self):
        """Return the newest non-expired key row, or an empty dict if none exist."""
        valid_keys = self.all_valid_keys()
        if not valid_keys:
            return {}
        return valid_keys[0]
    
    def expired_key(self):
        """Return the newest expired key row, or an empty dict if none exist."""
        with sqlite3.connect(self.databasepath) as conn:
            cursor = conn.cursor()
            res = cursor.execute(
                "SELECT * FROM keys WHERE exp <= ? ORDER BY kid DESC",
                (int(datetime.now(UTC).timestamp()),)
            )
            expired_keys = res.fetchall()
        if not expired_keys:
            return {}
        return expired_keys[0]

