from flask import Flask, jsonify, request
from datetime import datetime, timedelta, UTC
import jwt
import keyman
import keygen

'''Some of the code in this file was generated by Claude Sonnet 4.5
'''

app = Flask(__name__)

# Initialize the key manager with one valid key and one expired key
key_manager = keyman.KeyManager()
key_manager.create_key(datetime.now() + timedelta(hours=1))  # Valid key
key_manager.create_key(datetime.now() - timedelta(hours=1), debug=True)  # Expired key


@app.route('/auth', methods=['POST'])
def auth():
    """
    Authentication endpoint that issues JWTs.
    If ?expired=true is present, issues a JWT signed with an expired key.
    """
    # Check if expired query parameter is present
    expired = request.args.get('expired', 'false').lower() == 'true'
    
    #Expired JWT still needs to be done
    
    payload = {
        "sub": "user123",
        "iat": datetime.now(UTC),
    }

    if not expired:
        payload["exp"] = datetime.now(UTC) + timedelta(minutes=5)
        keydata = key_manager.newest_valid_key()
    else:
        payload["exp"] = datetime.now(UTC) - timedelta(minutes=5)
        keydata = key_manager.newest_expired_key()

    token = jwt.encode(payload, keydata["private_key"], algorithm="RS256", headers={"kid": keydata["jwk"]["kid"]})

    return jsonify({"token": token}), 200


@app.route('/.well-known/jwks.json', methods=['GET'])
def jwks():
    """
    JWKS endpoint that serves public keys in JWKS format.
    Only serves keys that have not expired.
    """
    
    keylist = key_manager.all_valid_keys()

    keys = {
        "keys": [k["jwk"] for k in keylist]
    }
    
    return jsonify(keys), 200


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True)