from flask import Flask, jsonify, request
import jwt
import os
import keyman
import userman
from datetime import datetime, timedelta, UTC
from cryptography.hazmat.primitives import serialization

# Some of the code in this file was generated by Claude Sonnet 4.5
# any line that has a comment with * in it was generated or partially generated


#Create database connection

app = Flask(__name__) # * sets up flask
# Initialize the key manager with one valid key and one expired key

key_manager = keyman.KeyManager()
key_manager.create_key(datetime.now() + timedelta(hours=1))  # Valid key
key_manager.create_key(datetime.now() - timedelta(hours=1), debug=True)  # Expired key
user_management = userman.userman()


@app.route('/auth', methods=['POST']) # * declares the path and method call for this function
def auth():
    """
    Authentication endpoint that issues JWTs.
    If ?expired=true is present, issues a JWT signed with an expired key.
    """
    # Check if expired query parameter is present
    expired = request.args.get('expired', 'false').lower() == 'true'
    
    #Expired JWT still needs to be done
    
    payload = request.get_json()
    

    if not expired:
        payload["exp"] = datetime.now(UTC) + timedelta(minutes=5)
        keydata = key_manager.valid_key()
    else:
        payload["exp"] = datetime.now(UTC) - timedelta(minutes=5)
        keydata = key_manager.expired_key()

    if not keydata:
        return jsonify({"error": "no keys are available"}) ,400

    private_key = serialization.load_pem_private_key(
        keydata[1],
        os.getenv("KEYPASSWORD").encode("utf-8")
    )
    kid = str(keydata[0])

    token = jwt.encode(payload, private_key, algorithm="RS256", headers={"kid": kid})

    return jsonify({"token": token}), 200


@app.route('/.well-known/jwks.json', methods=['GET']) # * Declares the path and method required for the function to run
def jwks():
    """
    JWKS endpoint that serves public keys in JWKS format.
    Only serves keys that have not expired.
    """
    
    keylist = key_manager.all_valid_keys()
    if len(keylist) == 0:
        return jsonify({"error": "no valid keys available"}), 400
    
    keys = {
        "keys": [key_manager.key_row_to_jwk(row) for row in keylist]
    }

    return jsonify(keys), 200

@app.route('/register', methods=['POST'])
def register():
    data = request.get_json()
    password = user_management.create_user(data['username'], data['email'])
    if password != "":
        return jsonify({'password': password}), 201
    else:
        return jsonify({'password': password}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True) # * runs flask if this file is being ran directly